### PR TITLE
Textures Repaint

### PR DESCRIPTION
**Pull request by Martian-Taiwan**
I repainted some textures and add some details for them. I also modify the acf file to make the aircraft's engine L and engine R parallel.

### CODE REVIEW

**Review by FBI914XB — COMMENTED** [review]
I checked the textures in sim, and the PBR does not seem to be reflective enough...

**Comment by FBI914XB** [comment]
The textures you made are great, as is the sidestick, however I think that my normal maps look better.

**Comment by FBI914XB** [comment]
Also I can't open the ACF, so it is not showing up in X-Plane

**Comment by FBI914XB** [comment]
Sorry one more thing I forgot: We have a custom EFB we will be implementing, so there's no need for avitab

**Comment by Martian-Taiwan** [comment]
OK, I know. I will repaint them

**Comment by FBI914XB** [comment]
Alright, I'm almost ready to approve the merge. Just need to know what changes you made in the "improve aircraft" commit where you made changes to the ACF file

**Comment by FBI914XB** [comment]
And the decals on the fuselage doors seem to be very low resolution... any chance you can improve that?

**Comment by FBI914XB** [comment]
Oh and make sure you update the ACF to have all the misc objects the ACF in the master branch has

**Comment by Martian-Taiwan** [comment]
Hi, I checked the ACF file just now. The plane has all the misc objects the ACF file in the master branch has.
About "improve aircraft" commit. I made the engines appear to be parallel.

**Comment by Martian-Taiwan** [comment]
The decals on the doors are low resolution? OK, I'll repaint them.

**Comment by Martian-Taiwan** [comment]
Hi, I make those decals from photos to words. So, now the decals are high resolution.

**Comment by Martian-Taiwan** [comment]
I updated the normal map to make it compatible with the new texture.

**Comment by FBI914XB** [comment]
Thanks! I'll merge now. Nice work!

**Review by FBI914XB — DISMISSED** [review]

**Comment by FBI914XB** [comment]
Screen Shot 2022-12-26 at 6 51 13 AM

I recommend you make a copy of my ACF file, found at https://github.com/x-bureau/Airbus-A318/blob/master/A318.acf, and then re-add your changes here

**Comment by Martian-Taiwan** [comment]
I made a copy of your a318 ACF file and re-added the changes. I also updated some icons.

**Review by FBI914XB — APPROVED** [review]

**Pull request merged**
